#!/bin/bash

cd ~
git clone https://github.com/m-dziuba/nixos.git
cd nixos
mv configuration.nix /etc/nixos/configuration.nix
cd ..
mv nixos ~/.config/home-manager
sudo nixos-rebuild switch
home-manager switch


