start-at-login = true

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = true

after-startup-command = ['exec-and-forget sketchybar', 'layout tiles']

# Notify Sketchybar about workspace change
exec-on-workspace-change = [
    "/usr/bin/env",
    "zsh",
    "-c",
    "source ~/.zshrc && sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE",
]


[gaps]
inner.vertical = 15
inner.horizontal = 15
outer.top = 50
outer.bottom = 20
outer.left = 20
outer.right = 20

[mode.main.binding]
alt-shift-semicolon = 'mode service'

cmd-h = []     # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

cmd-shift-enter = [
    'exec-and-forget ~/.config/aerospace/scripts/center_window.sh',
    'move-mouse window-force-center',
]

cmd-n = 'focus left'
cmd-e = 'focus down'
cmd-i = 'focus up'
cmd-o = 'focus right'

cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'

cmd-alt-1 = ['move-node-to-workspace 1', 'workspace 1']
cmd-alt-2 = ['move-node-to-workspace 2', 'workspace 2']
cmd-alt-3 = ['move-node-to-workspace 3', 'workspace 3']
cmd-alt-4 = ['move-node-to-workspace 4', 'workspace 4']
cmd-alt-5 = ['move-node-to-workspace 5', 'workspace 5']

cmd-alt-n = 'move left'
cmd-alt-e = 'move down'
cmd-alt-i = 'move up'
cmd-alt-o = 'move right'

cmd-alt-l = 'layout tiles horizontal vertical'
cmd-alt-u = 'resize smart +20'
cmd-alt-y = 'resize smart -20'

cmd-alt-f = 'fullscreen'

alt-f = 'layout floating tiling'
shift-cmd-c = 'close'

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
if.app-name-regex-substring = 'settings'
run = ['layout floating']


[[on-window-detected]]
if.app-id = 'com.apple.finder'
if.app-name-regex-substring = 'finder'
run = ['layout floating']


[[on-window-detected]]
if.app-id = 'org.jkiss.dbeaver.core.product'
if.app-name-regex-substring = 'DBeaver'
run = ['move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'org.jkiss.dbeaver.core.product'
if.app-name-regex-substring = 'DBeaver'
if.window-title-regex-substring = "Can't|update"
run = ['layout floating']
