#!/usr/bin/env bash
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m space 2 --label notes
yabai -m space 3 --label work
yabai -m space 4 --label other


# window rules
yabai -m rule --add app="^Firefox$" space=^work grid=2:3:2:0:1:2
yabai -m rule --add app="^WezTerm$" space=^work grid=2:3:1:0:1:2
yabai -m rule --add app="^Obsidian$" space=^notes
yabai -m rule --add app="^Spotify$" space=^work grid=2:3:1:0:1:1
yabai -m rule --add app="^Slack$" space=^work grid=2:3:0:0:1:1 manage=off
yabai -m rule --add app="^(Calculator|System Preferences|Archive Utility)$" space=^other manage=off

# signals
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null; fi"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_moved action="yabai -m window --focus $(yabai -m query --windows --window | jq -re '.id')"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config display_arrangement_order    default

## SIP stuff
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config window_animation_duration    0.5            
yabai -m config window_animation_easing      ease_out_quint 

# mouse
yabai -m config mouse_modifier               cmd
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config external_bar                 all:40:0
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   15

yabai -m signal --add event=application_launched action="/Users/mateusz/.config/nix/home/dotfiles/yabai/centerOneApp.sh"
yabai -m signal --add event=application_terminated action="/Users/mateusz/.config/nix/home/dotfiles/yabai/centerOneApp.sh"
yabai -m signal --add event=application_front_switched action="/Users/mateusz/.config/nix/home/dotfiles/yabai/centerOneApp.sh"
yabai -m signal --add event=space_changed action="/Users/mateusz/.config/nix/home/dotfiles/yabai/centerOneApp.sh"
